### ISSUE TITLE
VehicleData failures

### ISSUE THREAD

**Issue by jacobkeeler** [smartdevicelink/sdl_atf_test_scripts#1890]
The following VehicleData tests (submitted in #1714) currently fail against the `develop` branch of Core:

1. `test_scripts/API/VehicleData/SubscribeVehicleData/003_RPC_parameter_already_subscribed_Result_IGNORED_flow.lua`
2. `test_scripts/API/VehicleData/OnVehicleData/003_NotificationParameterDisallowedByPolicies_Ignored_flow.lua`
3. `test_scripts/API/VehicleData/SubscribeVehicleData/002_RPC_parameter_DISALLOWED_by_policies_flow.lua`

It should be investigated whether these are Core issues (in which case issues should be submitted to the Core repository) or bad test cases.

**Comment by dboltovskyi** [comment]
@jacobkeeler Test scripts in #1714 are created for [New-vehicle-data-EngineOilLife](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0082-New-vehicle-data-EngineOilLife.md) feature and have to be run within Core [#1823](https://github.com/smartdevicelink/sdl_core/pull/1823)
It's expected that they are failed on Core ```develop``` until PR is merged

**Comment by jacobkeeler** [comment]
@dboltovskyi Hello, smartdevicelink/sdl_core#1823 has many unnecessary changes for the feature it was supposed to implement. Based on these test failures, it would appear that one of the additional changes is resolving https://github.com/smartdevicelink/sdl_core/issues/1581.

What other fixes were implemented in this PR besides the original feature and https://github.com/smartdevicelink/sdl_core/issues/1581?

(@AKalinich-Luxoft as well, since they wrote the original Core PR)

**Comment by dboltovskyi** [comment]
@jacobkeeler 
Let me explain the reason of failed scripts.

Script (1):
  - SubscribeVehicleData/003_RPC_parameter_already_subscribed_Result_IGNORED_flow.lua

According to the requirements IGNORED result code is treated as success=false, but currently SDL sends success=true


Script (2) & (3):
  - OnVehicleData/003_NotificationParameterDisallowedByPolicies_Ignored_flow.lua
  - SubscribeVehicleData/002_RPC_parameter_DISALLOWED_by_policies_flow.lua

Both are related to the case:
```
In case if some parameters (e.g. 'engineOilLife' or 'fuelRange') are not allowed in PT for some RPC.
And some mobile app tries to send request (or get notification) with these parameters only.
SDL should disallow processing of request (or notification):
In case of request (SubscribeVehicleData/UnsubscribeVehicleData) mobile app will get DISALLOWED response.
In case of notification (OnVehicleData) app will get nothing (notification from HMI will be ignored).
```

I did some investigation:

Scripts mentioned are related to features:
  - [0082-New-vehicle-data-EngineOilLife](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0082-New-vehicle-data-EngineOilLife.md)
  - [0072-New-vehicle-data-FuelRange](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0072-New-vehicle-data-FuelRange.md)

There are 2 implementation tasks:
  - https://github.com/smartdevicelink/sdl_core/issues/1733
  - https://github.com/smartdevicelink/sdl_core/issues/1656

And there are 2 PRs for each task:
  - issue/1733:
  	- https://github.com/smartdevicelink/sdl_core/pull/1823
  	- https://github.com/smartdevicelink/sdl_core/pull/2157
  - issue/1656:
  	- https://github.com/smartdevicelink/sdl_core/pull/1822
  	- https://github.com/smartdevicelink/sdl_core/pull/2168

PRs 1822 and 1823 were closed since solution from PRs 2157 and 2168 was choosen.
But closed PRs has the fixes:
  - https://github.com/smartdevicelink/sdl_core/pull/1840
  - https://github.com/smartdevicelink/sdl_core/pull/1839

These fixes allow to remove some parameters in a list of allowed for RPCs in Policy Table (PT) during PT update.
Unfortunately these fixes are missing in develop branch. 
So there is no possibility to remove parameters.
And therefore requests/notifications with them are allowed.

**Comment by jacobkeeler** [comment]
Vehicle Data ATF tests have been revamped, so this issue is no longer relevant
