### ISSUE TITLE
Script for issue 2442 is not adapted for external policy flow

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_atf_test_scripts#2328]
SDL:https://github.com/smartdevicelink/sdl_core/commit/49f5b211ca995193d68301b0b3c08e3df427568f
Scripts: https://github.com/smartdevicelink/sdl_atf_test_scripts/commit/1f664c4b297046c8d7fa46d655dd75d4f6c72cbb
ATF: develop

Script https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/6_1/2442_Fix_mem_seg_fault_error_in_jsoncpp.lua is failed on external policy flow

**Comment by dboltovskyi** [comment]
Closed, since script works fine at `EXTERNAL_PROPRIETARY` policy flow for environment:
 - sdl_core: https://github.com/smartdevicelink/sdl_core/tree/develop (08d12403)
 - sdl_atf_test_scripts: https://github.com/smartdevicelink/sdl_atf_test_scripts/tree/develop (3969575)
 - sdl_atf: https://github.com/smartdevicelink/sdl_atf/tree/develop (f2d763d)
